[settings]
fulcio-url = http://sigstore-fulcio:5000 
rekor-url = http://sigstore-rekor:3000 
oauth_issuer-url = http://sigstore-dex:6000
diverify-url = http://localhost:8001
; tuf_url = http://localhost:8081
